spring.application.name=demo-entornos

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update

# Indica a Hibernate que cree las tablas y luego ejecute import.sql
spring.jpa.hibernate.ddl-auto=create-drop
# Asegura que se procese el archivo de scripts
spring.sql.init.mode=always

# 3. (Opcional) Si tu archivo se llama diferente o quieres ser explícito
spring.jpa.defer-datasource-initialization=true

# 4. Mostrar el log para saber qué está pasando realmente
logging.level.org.hibernate.tool.schema=DEBUG
spring.jpa.show-sql=true


# Si el script falla, la aplicación no debe arrancar (así veremos el error)
spring.sql.init.continue-on-error=false